name: intelligence_example
description: "Demonstrates how to use the intelligence plugin."
publish_to: 'none'

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  drawing_animation: ^1.0.1
  flutter:
    sdk: flutter

  intelligence:
    # When depending on this package from a real application you should use:
    #   intelligence: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  
  montelints: ^1.0.0+2

flutter:
  uses-material-design: true

  assets:
    - assets/
